version: 2

jobs:
  build:
    branches:
      only:
        - master
        - build-v2
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - run: git config --global user.name "Florian Weber (via CircleCI)"
      - run: git config --global user.email "florian@webflo.org"
      - add_ssh_keys
      - run: ./build/build.sh
